title: Jong-Chan Kim
logo: /assets/img/640.png
description: Ph.D. Senior Researcher at the Dep. Supercomputing Acceleration Research, KISTI
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
